apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: existing-single-central-noport-noingress-noautodeploy-20250904090946
build:
  tagPolicy:
    sha256: {}
  platforms: ["linux/amd64", "darwin/arm64"]
  artifacts:
  - image: ghcr.io/koala-tests/existing-single-central-noport-noingress-noautodeploy-20250904090946
    custom:
      buildCommand: ./build.sh
      dependencies:
        paths:
          - "go.mod"
          - "**/*.go"
manifests:
  kustomize:
    paths:
    - deploy/overlays/dev
profiles:
- name: prod
  manifests:
    kustomize:
      paths:
      - deploy/overlays/prod
